# Generated by Django 5.1.1 on 2024-09-23 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('club', 'Club Jersey'), ('nation', 'Nation Jersey')], max_length=255),
        ),
    ]
