# Generated by Django 5.1.1 on 2024-09-08 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jersey',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
