# Generated by Django 5.1.1 on 2024-09-08 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_jersey_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jersey',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
