# Generated by Django 5.1.1 on 2024-09-09 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_jersey_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jersey',
            new_name='Product',
        ),
    ]
